/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import org.jetbrains.compose.web.dom.Button
import org.jetbrains.compose.web.dom.Text
import org.jetbrains.compose.web.renderComposable

class App {
    val greeting: String
        get() = "Hello World!"
}

fun main() {
    renderComposable(rootElementId = "root") {
        var count by remember { mutableStateOf(0) }

        Button ( attrs =  {
            onClick { count++ }
        }) {
            Text("Clicked $count times")
        }
    }
    println(App().greeting)
}
